### ISSUE TITLE
Retry requires user to be public member of trusted organization

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [twbs/savage#29]
A user wishing to use the `@twbs-savage retry` syntax must not only be a member of the trusted organization, as is currently specified in the README.md, but they **must** be a public member.  

I suppose in the spirit of this project, that makes sense.  Alternatively, you could use `isMember` as opposed to `isPublicMember`.

At a minimum, I'm hoping #28 could be accepted to save future users the headache.

**Comment by cvrebert** [comment]
@Blackbaud-BobbyEarl Yeah, I'm open to being convinced otherwise (perhaps there's some use case I hadn't considered), but the rationale for the current behavior is that
(a) it avoids the possibility of accidentally revealing private org memberships
(b) if the bot responds to your command, then it's going to be pretty obvious that you're a member of the relevant organization anyway, so what's the point of trying to keep your membership private.

Also, if you end up using Savage, I'd love to add your project to the users list in the README :smile:

**Comment by Blackbaud-BobbyEarl** [comment]
Thanks for the quick reply and merge @cvrebert.  I agree with your use-cases and think the current behavior is the way to go.  We're using Savage and would be happy to have you add us to the users list.  

https://github.com/blackbaud/skyux

The only change to implementation from the default is our use of BrowserStack instead of Sauce Labs.  I've edited the source to change the comment that's added to a pull request to reflect that, but perhaps it would make sense to make that configurable.

Thanks for releasing Savage!

**Comment by cvrebert** [comment]
> I agree with your use-cases and think the current behavior is the way to go.

I'll close out this issue then.

> I've edited the source to change the comment that's added to a pull request to reflect that, but perhaps it would make sense to make that configurable.

I would happily accept a pull request that added such a setting and used some lightweight templating system to generate the comment. Only reason I haven't done it myself is that it's pretty low on my priorities list.

> Thanks for releasing Savage!

You're welcome. I hope it serves you well.

**Comment by cvrebert** [comment]
> We're using Savage and would be happy to have you add us to the users list.

Super! Added in 41cab0cdcfc30fad2f5e1d12406985b9360beaa4.
